language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - hhvm
sudo: false
env:
addons:
  apt:
    packages:
      - nodejs
before_script:
  - composer install

# Code coverage
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php -S localhost:8000 -t public server.php
    - vendor/bin/phpunit --coverage-clover=coverage.xml
    - phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)
