language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - hhvm
sudo: false
env:
addons:
  apt:
    packages:
      - nodejs
before_script:
  - composer install

script:
  - phpunit

# Code coverage
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml
    - php artisan serve

after_success:
    - bash <(curl -s https://codecov.io/bash)
