language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - hhvm
sudo: false
env:
addons:
  apt:
    packages:
      - nodejs
before_script:
  - composer install

script:
  - phpunit

# Code coverage
before_install:
  - pip install codecov
after_success:
  - codecov